import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  MUTATION_PR_GENERATOR_CONTRACT,
  createMutationPrManifest,
  createNVersionAuditRouting,
  generateMutationPrManifest,
  runEvolutionGuard,
  runMutationPrGenerator,
  runT051MutationPrGenerator,
  validateMutationPrGeneratorResult,
  validateMutationPrManifest,
  validateT051MutationPrGenerator,
} from "../dist/index.js";

const NOW = "2026-07-05T00:00:00Z";

function proposal(overrides = {}) {
  return {
    proposal_id: "speciation-proposal-11111111",
    mutation_id: "mut-22222222",
    mutation_class: "speciation",
    risk: "high",
    approval_class: "C",
    target_paths: [".forge/agents/planner.alpha.forge", ".forge/agents/planner.scoper.forge"],
    source_digest: "sha-fnv1a-abcdef12",
    ...overrides,
  };
}

function reviewer(overrides = {}) {
  return {
    reviewer_id: "architecture-reviewer",
    independence_key: "org-architecture",
    focuses: ["architecture", "lineage"],
    max_parallel_assignments: 1,
    ...overrides,
  };
}

function routing() {
  return createNVersionAuditRouting({
    now: NOW,
    proposal: proposal(),
    reviewers: [
      reviewer({ reviewer_id: "state-reviewer", independence_key: "org-state", focuses: ["state", "tests"] }),
      reviewer(),
      reviewer({ reviewer_id: "security-reviewer", independence_key: "org-security", focuses: ["security"] }),
      reviewer({ reviewer_id: "lineage-reviewer", independence_key: "org-lineage", focuses: ["lineage"] }),
    ],
    policy: {
      min_reviewers: 3,
      required_quorum: 2,
      required_focuses: ["architecture", "security", "lineage"],
    },
  });
}

function reviewFor(route, routingResult, index = 0, overrides = {}) {
  return {
    route_id: route.route_id,
    reviewer_id: route.reviewer_id,
    independence_key: route.independence_key,
    decision: "approve",
    completed_at: NOW,
    routing_digest: routingResult.routing_digest,
    reviewed_target_paths: routingResult.proposal.target_paths,
    findings: [],
    evidence_digest: `sha-fnv1a-def0000${index}`,
    ...overrides,
  };
}

function acceptedGuard(overrides = {}) {
  const routingResult = routing();
  return runEvolutionGuard({
    now: NOW,
    proposal: routingResult.proposal,
    routing: routingResult,
    reviews: routingResult.reviewer_routes.map((route, index) => reviewFor(route, routingResult, index)),
    ...overrides,
  });
}

describe("T051 mutation PR generator", () => {
  it("declares a deterministic manifest-only PR plan contract", () => {
    assert.equal(MUTATION_PR_GENERATOR_CONTRACT.deterministic, true);
    assert.equal(MUTATION_PR_GENERATOR_CONTRACT.manifestOnly, true);
    assert.ok(MUTATION_PR_GENERATOR_CONTRACT.validates.includes("accepted_evolution_guard_only"));
    assert.ok(MUTATION_PR_GENERATOR_CONTRACT.validates.includes("safe_branch_refs"));
    assert.ok(MUTATION_PR_GENERATOR_CONTRACT.forbids.includes("github_api_call"));
    assert.ok(MUTATION_PR_GENERATOR_CONTRACT.forbids.includes("git_push"));
    assert.ok(MUTATION_PR_GENERATOR_CONTRACT.forbids.includes("merge_operation"));
  });

  it("creates a deterministic draft PR manifest only from an accepted EvolutionGuard decision", () => {
    const guard = acceptedGuard();
    assert.equal(guard.decision, "evolution_guard_accept", JSON.stringify(guard, null, 2));

    const result = runMutationPrGenerator({
      now: NOW,
      guard,
      repository: "hiroshitanaka-creator/ForgeRoot",
      labels: ["t051"],
      reviewers: ["@maintainer-one"],
      body_notes: ["generated by test"],
    });

    assert.equal(result.status, "pr_manifest_ready", JSON.stringify(result, null, 2));
    assert.equal(result.decision, "mutation_pr_manifest_ready");
    assert.equal(result.repository, "hiroshitanaka-creator/ForgeRoot");
    assert.equal(result.guard_ref.guard_id, guard.guard_id);
    assert.equal(result.guard_ref.decision, "evolution_guard_accept");
    assert.equal(result.pull_request.draft, true);
    assert.equal(result.pull_request.maintainer_can_modify, false);
    assert.ok(result.pull_request.head.startsWith("codex/t051-"));
    assert.equal(result.pull_request.base, "main");
    assert.ok(result.pull_request.body.includes("No GitHub API call"));
    assert.ok(result.pull_request.labels.includes("forge:mutation-pr"));
    assert.ok(result.pull_request.labels.includes("t051"));
    assert.deepEqual(result.pull_request.reviewers, ["maintainer-one"]);
    assert.deepEqual(result.scope.target_paths, guard.proposal.target_paths);
    assert.equal(result.guards.no_github_api_call, true);
    assert.equal(result.guards.no_git_push, true);
    assert.equal(result.guards.no_merge_operation, true);
    assert.equal(result.dry_run.github_api_called, false);
    assert.equal(result.dry_run.git_push_performed, false);
    assert.equal(result.dry_run.branch_created, false);
    assert.deepEqual(validateMutationPrGeneratorResult(result), { ok: true, issues: [] });
    assert.deepEqual(validateMutationPrManifest(result), { ok: true, issues: [] });

    const replay = runMutationPrGenerator({ now: NOW, guard, repository: "hiroshitanaka-creator/ForgeRoot", labels: ["t051"], reviewers: ["@maintainer-one"], body_notes: ["generated by test"] });
    assert.equal(replay.plan_id, result.plan_id);
    assert.equal(replay.plan_digest, result.plan_digest);
    assert.deepEqual(replay.pull_request, result.pull_request);
  });

  it("blocks hold and reject EvolutionGuard decisions without producing PR metadata", () => {
    const routingResult = routing();
    const holdGuard = runEvolutionGuard({
      now: NOW,
      proposal: routingResult.proposal,
      routing: routingResult,
      reviews: routingResult.reviewer_routes.slice(0, 2).map((route, index) => reviewFor(route, routingResult, index)),
    });
    const rejectGuard = runEvolutionGuard({
      now: NOW,
      proposal: routingResult.proposal,
      routing: routingResult,
      reviews: routingResult.reviewer_routes.map((route, index) => reviewFor(route, routingResult, index, index === 0 ? { decision: "reject" } : {})),
    });

    for (const guard of [holdGuard, rejectGuard]) {
      const result = runMutationPrGenerator({ now: NOW, guard });
      assert.equal(result.status, "blocked", JSON.stringify(result, null, 2));
      assert.equal(result.decision, "mutation_pr_blocked_by_guard");
      assert.equal(result.pull_request, undefined);
      assert.match(result.plan_digest, /^sha-fnv1a-[0-9a-f]{8}$/);
      assert.ok(result.reasons.includes("guard_not_accepted"));
      assert.deepEqual(validateMutationPrGeneratorResult(result), { ok: true, issues: [] });
    }
  });

  it("invalidates tampered accepted guards and unsafe PR metadata", () => {
    const guard = acceptedGuard();
    const tamperedGuard = runMutationPrGenerator({ now: NOW, guard: { ...guard, guard_digest: "sha-fnv1a-00000000" } });
    assert.equal(tamperedGuard.status, "invalid");
    assert.ok(tamperedGuard.reasons.includes("invalid_evolution_guard_manifest"));
    assert.deepEqual(validateMutationPrGeneratorResult(tamperedGuard), { ok: true, issues: [] });

    const unsafeBranch = runMutationPrGenerator({ now: NOW, guard, base_branch: "main", head_branch: "main" });
    assert.equal(unsafeBranch.status, "invalid");
    assert.ok(unsafeBranch.reasons.includes("default_branch_write_forbidden"));

    const unsafeRepository = runMutationPrGenerator({ now: NOW, guard, repository: "not a repo" });
    assert.equal(unsafeRepository.status, "invalid");
    assert.ok(unsafeRepository.reasons.includes("invalid_repository"));

    const unsafeLabel = runMutationPrGenerator({ now: NOW, guard, labels: ["bad\nlabel"] });
    assert.equal(unsafeLabel.status, "invalid");
    assert.ok(unsafeLabel.reasons.includes("unsafe_label"));

    const secretNote = runMutationPrGenerator({ now: NOW, guard, body_notes: ["github_pat_abc123"] });
    assert.equal(secretNote.status, "invalid");
    assert.ok(secretNote.reasons.includes("secret_material_forbidden"));
    assert.equal(JSON.stringify(secretNote).includes("github_pat_abc123"), false);
    assert.deepEqual(validateMutationPrGeneratorResult(secretNote), { ok: true, issues: [] });

    const secretLabel = runMutationPrGenerator({ now: NOW, guard, labels: ["github_pat_abc123"] });
    assert.equal(secretLabel.status, "invalid");
    assert.ok(secretLabel.reasons.includes("secret_material_forbidden"));
    assert.equal(JSON.stringify(secretLabel).includes("github_pat_abc123"), false);
  });

  it("clones guard proposal metadata before returning the PR manifest", () => {
    const guard = acceptedGuard();
    const result = runMutationPrGenerator({ now: NOW, guard });

    guard.proposal.target_paths.push(".forge/agents/mutated.alpha.forge");

    assert.deepEqual(result.proposal.target_paths, [".forge/agents/planner.alpha.forge", ".forge/agents/planner.scoper.forge"]);
    assert.deepEqual(result.scope.target_paths, [".forge/agents/planner.alpha.forge", ".forge/agents/planner.scoper.forge"]);
  });

  it("rejects tampered PR manifests, side effects, guard weakening, and stale digests", () => {
    const result = runMutationPrGenerator({ now: NOW, guard: acceptedGuard() });
    assert.equal(result.status, "pr_manifest_ready", JSON.stringify(result, null, 2));

    const gitPush = {
      ...result,
      dry_run: { ...result.dry_run, git_push_performed: true },
    };
    assert.equal(validateMutationPrGeneratorResult(gitPush).ok, false);
    assert.ok(validateMutationPrGeneratorResult(gitPush).issues.some((entry) => entry.code === "side_effect_forbidden"));

    const weakGuard = {
      ...result,
      guards: { ...result.guards, no_github_api_call: false },
    };
    assert.equal(validateMutationPrGeneratorResult(weakGuard).ok, false);
    assert.ok(validateMutationPrGeneratorResult(weakGuard).issues.some((entry) => entry.path === "guards.no_github_api_call"));

    const defaultBranch = {
      ...result,
      pull_request: { ...result.pull_request, head: "main" },
    };
    assert.equal(validateMutationPrGeneratorResult(defaultBranch).ok, false);
    assert.ok(validateMutationPrGeneratorResult(defaultBranch).issues.some((entry) => entry.code === "unsafe_head_branch" || entry.code === "default_branch_write_forbidden"));

    const staleDigest = {
      ...result,
      plan_digest: "sha-fnv1a-00000000",
    };
    assert.equal(validateMutationPrGeneratorResult(staleDigest).ok, false);
    assert.ok(validateMutationPrGeneratorResult(staleDigest).issues.some((entry) => entry.code === "plan_digest_mismatch"));

    const blockedWithPr = {
      ...runMutationPrGenerator({ now: NOW, guard: acceptedGuard({ reviews: [] }) }),
      pull_request: result.pull_request,
    };
    assert.equal(validateMutationPrGeneratorResult(blockedWithPr).ok, false);
    assert.ok(validateMutationPrGeneratorResult(blockedWithPr).issues.some((entry) => entry.code === "terminal_pr_forbidden"));
  });

  it("supports stable aliases", () => {
    for (const fn of [createMutationPrManifest, generateMutationPrManifest, runT051MutationPrGenerator]) {
      const result = fn({ now: NOW, guard: acceptedGuard() });
      assert.equal(result.status, "pr_manifest_ready");
      assert.deepEqual(validateT051MutationPrGenerator(result), { ok: true, issues: [] });
    }
  });
});
